import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, ChevronRight, CircleDot, FilePlus2, FileText, Filter, FolderKanban, Globe2, MapPinned, MoreHorizontal, Search, ShieldCheck, Sparkles, Target, TrendingUp } from 'lucide-react';
import type { NationalStats, ParcelRecord, ProjectData, ViewTab } from '../../types';
import { Metric, MiniMap, ProjectRow, RiskPill, SignalBar, riskTone } from '../ui';

export function RiskStudio({ projects, onSelect }: { projects: ProjectData[]; onSelect: (p: ProjectData) => void }) {
  const average = Math.round(projects.reduce((sum, p) => sum + p.riskScore, 0) / projects.length);
  return <div className="page-stack"><section className="page-heading"><div><div className="eyebrow">EXPLAINABLE PREDICTION LAYER</div><h1>Risk studio</h1><p>Turn model output into an operational next step.</p></div><div className="model-status"><span className="live-dot" /> Model v1.4.2 <small>validated 2 days ago</small></div></section><section className="studio-grid"><div className="panel model-card"><div className="panel-heading"><div><span className="eyebrow">National signal</span><h2>Risk distribution</h2></div><Sparkles size={18} className="muted-icon" /></div><div className="big-score"><strong>{average}</strong><span>average risk score</span><div className="score-change"><TrendingUp size={14} /> 8 pts above last month</div></div><div className="distribution"><div className="distribution-bar"><i className="low" style={{ width: '32%' }} /><i className="medium" style={{ width: '28%' }} /><i className="high" style={{ width: '24%' }} /><i className="critical" style={{ width: '16%' }} /></div><div className="distribution-key"><span><i className="legend-dot stable" /> Low <b>402</b></span><span><i className="legend-dot medium" /> Medium <b>350</b></span><span><i className="legend-dot high" /> High <b>300</b></span><span><i className="legend-dot critical" /> Critical <b>196</b></span></div></div></div><div className="panel explain-card"><div className="panel-heading"><div><span className="eyebrow">Signal anatomy</span><h2>What moves risk</h2></div><span className="confidence">86% confidence</span></div><div className="factor-stack"><SignalBar label="Legal / dispute load" value={82} tone="coral" /><SignalBar label="Compensation progress" value={69} tone="coral" /><SignalBar label="Notification age" value={54} tone="ochre" /><SignalBar label="Stakeholder response" value={31} tone="teal" /><SignalBar label="R&R readiness" value={22} tone="teal" /></div><div className="insight-callout"><ShieldCheck size={17} /><span>Strongest risk reducer: <b>clear title records</b> in early-stage projects.</span></div></div></section><section className="panel analysis-table"><div className="panel-heading"><div><span className="eyebrow">Review queue</span><h2>Files with model movement</h2></div><button className="text-button">Download CSV <ChevronRight size={14} /></button></div>{projects.map((p) => <button className="analysis-row" key={p.id} onClick={() => onSelect(p)}><div className="analysis-name"><span className={`signal-badge ${riskTone(p.riskLevel).className}`}><Activity size={14} /></span><div><strong>{p.title}</strong><span>{p.id} · {p.district}</span></div></div><div><span className="micro-label">Delay likelihood</span><strong>{p.probabilityOfDelay}</strong></div><div><span className="micro-label">Top driver</span><strong>{p.shapFactors[0]?.driver}</strong></div><RiskPill level={p.riskLevel} /><ChevronRight size={16} /></button>)}</section></div>;
}
